// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockResolver creates a new instance of MockResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResolver {
	mock := &MockResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResolver is an autogenerated mock type for the Resolver type
type MockResolver struct {
	mock.Mock
}

type MockResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResolver) EXPECT() *MockResolver_Expecter {
	return &MockResolver_Expecter{mock: &_m.Mock}
}

// Route provides a mock function for the type MockResolver
func (_mock *MockResolver) Route(host string) (string, bool) {
	ret := _mock.Called(host)

	if len(ret) == 0 {
		panic("no return value specified for Route")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (string, bool)); ok {
		return returnFunc(host)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(host)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(host)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockResolver_Route_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Route'
type MockResolver_Route_Call struct {
	*mock.Call
}

// Route is a helper method to define mock.On call
//   - host string
func (_e *MockResolver_Expecter) Route(host any) *MockResolver_Route_Call {
	return &MockResolver_Route_Call{Call: _e.mock.On("Route", host)}
}

func (_c *MockResolver_Route_Call) Run(run func(host string)) *MockResolver_Route_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockResolver_Route_Call) Return(s string, b bool) *MockResolver_Route_Call {
	_c.Call.Return(s, b)
	return _c
}

func (_c *MockResolver_Route_Call) RunAndReturn(run func(host string) (string, bool)) *MockResolver_Route_Call {
	_c.Call.Return(run)
	return _c
}
