// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// All provides a mock function for the type MockStore
func (_mock *MockStore) All() map[string]string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 map[string]string
	if returnFunc, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	return r0
}

// MockStore_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type MockStore_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
func (_e *MockStore_Expecter) All() *MockStore_All_Call {
	return &MockStore_All_Call{Call: _e.mock.On("All")}
}

func (_c *MockStore_All_Call) Run(run func()) *MockStore_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_All_Call) Return(stringToString map[string]string) *MockStore_All_Call {
	_c.Call.Return(stringToString)
	return _c
}

func (_c *MockStore_All_Call) RunAndReturn(run func() map[string]string) *MockStore_All_Call {
	_c.Call.Return(run)
	return _c
}

// Replace provides a mock function for the type MockStore
func (_mock *MockStore) Replace(mappings map[string]string) {
	_mock.Called(mappings)
	return
}

// MockStore_Replace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Replace'
type MockStore_Replace_Call struct {
	*mock.Call
}

// Replace is a helper method to define mock.On call
//   - mappings map[string]string
func (_e *MockStore_Expecter) Replace(mappings any) *MockStore_Replace_Call {
	return &MockStore_Replace_Call{Call: _e.mock.On("Replace", mappings)}
}

func (_c *MockStore_Replace_Call) Run(run func(mappings map[string]string)) *MockStore_Replace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]string
		if args[0] != nil {
			arg0 = args[0].(map[string]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_Replace_Call) Return() *MockStore_Replace_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStore_Replace_Call) RunAndReturn(run func(mappings map[string]string)) *MockStore_Replace_Call {
	_c.Run(run)
	return _c
}
