# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HeaderSetterProxy < Formula
  desc "Local CONNECT proxy that routes a host to another host for the Header Setter Chrome extension"
  homepage "https://github.com/otto-wagner/header-setter"
  version "1.2.2"
  license "MIT"

  on_macos do
    url "https://github.com/otto-wagner/header-setter/releases/download/v1.2.2/header-setter-proxy_1.2.2_darwin_all.tar.gz"
    sha256 "db9505829a7f05fd6d54d0ea002ad57906ad197332cbb74618ee93ce00c828ea"

    define_method(:install) do
      bin.install "header-setter-proxy"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/otto-wagner/header-setter/releases/download/v1.2.2/header-setter-proxy_1.2.2_linux_amd64.tar.gz"
      sha256 "395754d43a677a3c3743bddc3ea42a2aa2951cbabaae3d8b821a66d4da7f2869"
      define_method(:install) do
        bin.install "header-setter-proxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/otto-wagner/header-setter/releases/download/v1.2.2/header-setter-proxy_1.2.2_linux_arm64.tar.gz"
      sha256 "ee183da3024fbd911f195f76afd9c5ce837e99b41852dfc6cd6d57f16aa5c42c"
      define_method(:install) do
        bin.install "header-setter-proxy"
      end
    end
  end

  test do
    assert_match "Routes selected hosts to a different target", shell_output("#{bin}/header-setter-proxy serve --help")
  end
end
