# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HeaderSetterProxy < Formula
  desc "Local CONNECT proxy that routes a host to another host for the Header Setter Chrome extension"
  homepage "https://github.com/otto-wagner/header-setter"
  version "1.5.3"
  license "MIT"

  on_macos do
    url "https://github.com/otto-wagner/header-setter/releases/download/v1.5.3/header-setter-proxy_1.5.3_darwin_all.tar.gz"
    sha256 "919b457c874c323b0a3602d4ab0b14a5d81cbb043c45000c0706cb664cb2fbf6"

    define_method(:install) do
      bin.install "header-setter-proxy"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/otto-wagner/header-setter/releases/download/v1.5.3/header-setter-proxy_1.5.3_linux_amd64.tar.gz"
      sha256 "4adfd350000de1765aa2413778373b3ee12248638b563053406dfe8bfb720150"
      define_method(:install) do
        bin.install "header-setter-proxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/otto-wagner/header-setter/releases/download/v1.5.3/header-setter-proxy_1.5.3_linux_arm64.tar.gz"
      sha256 "cf96279acbceb9c7b640cb14606c0a09f57835e57185dfe43b9c1c8a80c51241"
      define_method(:install) do
        bin.install "header-setter-proxy"
      end
    end
  end

  test do
    assert_match "Routes selected hosts to a different target", shell_output("#{bin}/header-setter-proxy serve --help")
  end
end
