# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HeaderSetterProxy < Formula
  desc "Local CONNECT proxy that routes a host to another host for the Header Setter Chrome extension"
  homepage "https://github.com/otto-wagner/header-setter"
  version "1.5.0"
  license "MIT"

  on_macos do
    url "https://github.com/otto-wagner/header-setter/releases/download/v1.5.0/header-setter-proxy_1.5.0_darwin_all.tar.gz"
    sha256 "1ddc289c7d27fe048597dcc28b01e0ed9ef506480999b34918b38909559b21de"

    define_method(:install) do
      bin.install "header-setter-proxy"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/otto-wagner/header-setter/releases/download/v1.5.0/header-setter-proxy_1.5.0_linux_amd64.tar.gz"
      sha256 "9f0233156928a9d74363a3c37524c0777c260e93ffe8a2656fa2ec737999ce19"
      define_method(:install) do
        bin.install "header-setter-proxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/otto-wagner/header-setter/releases/download/v1.5.0/header-setter-proxy_1.5.0_linux_arm64.tar.gz"
      sha256 "db3b35005cccd73ec3f84f97e180d83275d284ce49f0cb20a4ff116c9c4cf0af"
      define_method(:install) do
        bin.install "header-setter-proxy"
      end
    end
  end

  test do
    assert_match "Routes selected hosts to a different target", shell_output("#{bin}/header-setter-proxy serve --help")
  end
end
